// DO NOT EDIT. This file is generated by deco.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $$$$$$$$$$$0 from "./apps/deco/algolia.ts";
import * as $$$$$$$$$$$1 from "./apps/deco/blog.ts";
import * as $$$$$$$$$$$2 from "./apps/deco/htmx.ts";
import * as $$$$$$$$$$$3 from "./apps/deco/implementation.ts";
import * as $$$$$$$$$$$4 from "./apps/deco/linx-impulse.ts";
import * as $$$$$$$$$$$5 from "./apps/deco/records.ts";
import * as $$$$$$$$$$$6 from "./apps/deco/typesense.ts";
import * as $$$$$$$$$$$7 from "./apps/deco/workflows.ts";
import * as $$$$$$$$$$$8 from "./apps/site.ts";
import * as $$$$$$0 from "./sections/Footer.tsx";
import * as $$$$$$1 from "./sections/ItWorks.tsx";
import * as $$$$$$2 from "./sections/Theme/Theme.tsx";

const manifest = {
  "sections": {
    "site/sections/Footer.tsx": $$$$$$0,
    "site/sections/ItWorks.tsx": $$$$$$1,
    "site/sections/Theme/Theme.tsx": $$$$$$2,
  },
  "apps": {
    "site/apps/deco/algolia.ts": $$$$$$$$$$$0,
    "site/apps/deco/blog.ts": $$$$$$$$$$$1,
    "site/apps/deco/htmx.ts": $$$$$$$$$$$2,
    "site/apps/deco/implementation.ts": $$$$$$$$$$$3,
    "site/apps/deco/linx-impulse.ts": $$$$$$$$$$$4,
    "site/apps/deco/records.ts": $$$$$$$$$$$5,
    "site/apps/deco/typesense.ts": $$$$$$$$$$$6,
    "site/apps/deco/workflows.ts": $$$$$$$$$$$7,
    "site/apps/site.ts": $$$$$$$$$$$8,
  },
  "name": "site",
  "baseUrl": import.meta.url,
};

export type Manifest = typeof manifest;

export default manifest;
